version: "3.8"

networks:
  tethys:
    name: tethys
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.254.0/28

services:
  nats:
    container_name: nats
    build:
      context: docker/images/nats
    ports:
      - "4222:4222" # client connections
      - "6222:6222" # routing port for clustering
      - "8222:8222" # http management port for information reporting
    networks:
      - tethys

  geth-bootnode:
    container_name: geth-bootnode
    build:
      context: docker/images/geth
      args:
        - ACCOUNT_PASSWORD=${GETH_ACCOUNT_PASSWORD}
    command:
      --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
      --nodiscover
      --ipcdisable
      --networkid=${GETH_NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      - tethys

  geth-miner:
    container_name: geth-miner
    build:
      context: docker/images/geth
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --mine
      --miner.threads=1
      --networkid=${GETH_NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      tethys:

  geth-rpc-1:
    container_name: geth-rpc-1
    build:
      context: docker/images/geth
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --http
      --http.vhosts="*"
      --http.addr="0.0.0.0"
      --http.api="eth,net,eth,debug,txpool,personal,admin"
      --http.corsdomain="*"
      --http.rpcprefix="/"
      --ws
      --ws.addr="0.0.0.0"
      --ws.api="eth,net,eth,debug,txpool,personal,admin"
      --ws.rpcprefix="/"
      --networkid=${GETH_NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    ports:
      - "8545:8545"
      - "8546:8546"
    networks:
      - tethys

  geth-rpc-1-sidecar:
    container_name: geth-rpc-1-sidecar
    image: 41north/tethys-sidecar:dev
    depends_on:
      - nats
      - geth-rpc-1
    networks:
      - tethys
    restart: on-failure
    command:
      - eth
    environment:
      NATS_URL: ns://nats:4222
      WEB3_URL: ws://geth-rpc-1:8546

  geth-rpc-2:
    container_name: geth-rpc-2
    build:
      context: docker/images/geth
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --http
      --http.vhosts="*"
      --http.addr="0.0.0.0"
      --http.api="eth,net,eth,debug,txpool,personal,admin"
      --http.corsdomain="*"
      --http.rpcprefix="/"
      --ws
      --ws.addr="0.0.0.0"
      --ws.api="eth,net,eth,debug,txpool,personal,admin"
      --ws.rpcprefix="/"
      --networkid=${GETH_NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      - tethys

  geth-rpc-2-sidecar:
    container_name: geth-rpc-2-sidecar
    image: 41north/tethys-sidecar:dev
    depends_on:
      - nats
      - geth-rpc-2
    networks:
      - tethys
    restart: on-failure
    command:
      - eth
    environment:
      NATS_URL: ns://nats:4222
      WEB3_URL: ws://geth-rpc-2:8546

  geth-rpc-3:
    container_name: geth-rpc-3
    build:
      context: docker/images/geth
    depends_on:
      - geth-bootnode
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@geth-bootnode:30303"
      --http
      --http.vhosts="*"
      --http.addr="0.0.0.0"
      --http.api="eth,net,eth,debug,txpool,personal,admin"
      --http.corsdomain="*"
      --http.rpcprefix="/"
      --ws
      --ws.addr="0.0.0.0"
      --ws.api="eth,net,eth,debug,txpool,personal,admin"
      --ws.rpcprefix="/"
      --networkid=${GETH_NETWORK_ID}
      --netrestrict="172.16.254.0/28"
    networks:
      - tethys

  geth-rpc-3-sidecar:
    container_name: geth-rpc-3-sidecar
    image: 41north/tethys-sidecar:dev
    depends_on:
      - nats
      - geth-rpc-3
    networks:
      - tethys
    restart: on-failure
    command:
      - eth
    environment:
      NATS_URL: ns://nats:4222
      WEB3_URL: ws://geth-rpc-3:8546

  proxy:
    container_name: proxy
    image: 41north/tethys-proxy:dev
    depends_on:
      - nats
    networks:
      - tethys
    ports:
      - "8080:8080"
    restart: on-failure
    command:
      - eth
      - --log-level=debug
    environment:
      NATS_URL: ns://nats:4222
      ETH_NETWORK_ID: 1214
      ETH_CHAIN_ID: 1214
